all:
  children:
    aruba_switches:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: arubanetworks.aos_switch.arubaoss
        ansible_network_cli_ssh_type: paramiko
        ansible_user: "{{ lookup('env', 'ARUBA_USERNAME') }}"
        ansible_password: "{{ lookup('env', 'ARUBA_PASSWORD') }}"

      hosts:
        aruba3810m:
          ansible_host: 198.84.60.171
          ansible_port: 20022
          ansible_connect_timeout: 120
          ansible_command_timeout: 120
          ansible_terminal_initial_prompt:
            - '(?i)press.*(?:enter|any key).*continue'
          ansible_terminal_initial_answer:
            - ''
          ansible_terminal_initial_prompt_newline: true
